#!/bin/bash

# custom AppRun for ArtLight AppImage

# path of the extracted AppRun
HERE="$(dirname "$(readlink -f "${0}")")"
SUNSHINE_PATH=/usr/bin/artlight
SUNSHINE_BIN_HERE=$HERE/usr/bin/artlight
SUNSHINE_SHARE_HERE=$HERE/usr/share/artlight

# Set APPDIR when running directly from the AppDir:
if [ -z "$APPDIR" ]; then
    ARGV0="AppRun"
fi

cd "$HERE" || exit 1

function help() {
echo "
 ------------------------------
   ArtLight AppImage package.
 ------------------------------

 artlight.AppImage options
 ------------------------

 Usage:  $ARGV0  --help, -h
 ------            # This message

         $ARGV0  --install, -i
                   # Install input rules and artlight.service files. Restart required.

         $ARGV0  --remove, -r
                   # Remove input rules and artlight.service files.

         $ARGV0  --appimage-help
                   # Show available AppImage options

 artlight options
 ----------------
"
# print ArtLight binary help, replacing the command in the usage statement
"$SUNSHINE_BIN_HERE" --help | sed -e "s#$SUNSHINE_BIN_HERE#$ARGV0#g"
}

function install() {
  # user input rules
  # shellcheck disable=SC2002
  cat "$SUNSHINE_SHARE_HERE/udev/rules.d/60-sunshine.rules" | sudo tee /etc/udev/rules.d/60-sunshine.rules
  cat "$SUNSHINE_SHARE_HERE/modules-load.d/60-sunshine.conf" | sudo tee /etc/modules-load.d/60-sunshine.conf
  sudo modprobe uhid
  sudo udevadm control --reload-rules
  sudo udevadm trigger --property-match=DEVNAME=/dev/uinput
  sudo udevadm trigger --property-match=DEVNAME=/dev/uhid
  # Same reason as the Arch install hook: input devices have no fixed DEVNAME, and one that
  # is already present when the rules change is otherwise left holding its old permissions.
  sudo udevadm trigger --subsystem-match=input

  # ArtLight service
  mkdir -p ~/.config/systemd/user
  cp -r "$SUNSHINE_SHARE_HERE/systemd/user/" ~/.config/systemd/
  # patch service executable path
  sed -i -e "s#$SUNSHINE_PATH#$(readlink -f $ARGV0)#g" ~/.config/systemd/user/app-io.github.onaiaku.ArtLight.service

  # setcap
  sudo setcap cap_sys_admin,cap_sys_nice+p "$(readlink -f "$SUNSHINE_BIN_HERE")"
}

function remove() {
  # remove input rules
  sudo rm -f /etc/udev/rules.d/60-sunshine.rules

  # remove uhid module loading config
  sudo rm -f /etc/modules-load.d/60-sunshine.conf

  # remove service
  sudo rm -f ~/.config/systemd/user/app-io.github.onaiaku.ArtLight.service
}

# process arguments
if [ "x$1" == "xhelp" ] || [ "x$1" == "x--help" ] || [ "x$1" == "x-h" ] ; then
    help
    exit $?
fi

if [ "x$1" == "xinstall" ] || [ "x$1" == "x--install" ] || [ "x$1" == "x-i" ] ; then
    install
    exit $?
fi

if [ "x$1" == "xremove" ] || [ "x$1" == "x--remove" ] || [ "x$1" == "x-r" ] ; then
    remove
    exit $?
fi

# create config directory if it doesn't exist
# https://github.com/LizardByte/Sunshine/issues/324
mkdir -p ~/.config/artlight

# run ArtLight
"$SUNSHINE_BIN_HERE" $@
